### ISSUE TITLE
[PROPOSAL] Buat Input Diskon pada Invoice

### ISSUE THREAD

**Issue by nafiesl** [nafiesl/free-pmo#10]
Saat membuat invoice, terkadang ada **nilai diskon** yang diberikan pada invoice tersebut.

Misal satu invoice memiliki beberapa Item:
1. Tagihan server ... 1000
2. Tagihan Maintenance 3000
3. Tagihan .... 500

Subtotal **4500**
Diskon 100 (Diskon server dan maintenance)
Total : **4400**

Rencana Fitur :
- Pengisian diskon dilakukan saat **Edit Invoice**.
- Jika field diskon diisi (wajib), maka jumlah tagihan / kolom `amount` = total tagihan - diskon.
- Ada field keterangan diskon (optional) untuk mendeskripsikan diskon.
- Pada tabel `invoices` ditambahkan kolom `discount` int(10) dan `discount_notes` varchar(255).

**Comment by ad3n** [comment]
Mantab
