### ISSUE TITLE
[BUG] Di Kalender

### ISSUE THREAD

**Issue by diorz38** [nafiesl/free-pmo#14]
Ketika memindahkan (drag) event yang sebelumnya di set **All-Days** => true, keluar error:

`Error processing your request: {"message":"The given data was invalid.","errors":{"end":["The end is not a valid date.","The end does not match the format Y-m-d H:i:s."]}}`

> Saya sedikit menambahkan option baru pd jscript fullcalendar-nya yaitu:
```
minTime: '07:00:00',
maxTime: '17:30:00',
eventLimit: true,
businessHours: {
    // days of week. an array of zero-based day of week integers (0=Sunday)
    dow: [ 1, 2, 3, 4, 5 ],
    start: '07:00',
    end: '17:30',
    },
```
tetapi ketika mengembalikan ke setting default pun keluar error yang sama.
![errorpmo1](https://user-images.githubusercontent.com/4964821/44310651-ff4e9f80-a403-11e8-90e6-a0a068a9c68e.jpg)

#### [PROPOSAL] Penambahan button di kalender untuk opsi enable/disable untuk add/edit, karena cukup membatu pada saat navigasi pemeriksaan konten kalender dan terhindar dari perubahan tidak sengaja isi konten kalender tsb.

Terimakasih,

Salam PMO!!!

**Comment by nafiesl** [comment]
Bug fixed mas @diorz38, silakan coba `git pull` mas.

**Comment by diorz38** [comment]
Terimakasih mas. 👍 👍 for usual fast respond-nya

Betul sekali seperti itu mas, semacam tombol opsi on=can edit or add, off=view-only

**Comment by nafiesl** [comment]
mas @diorz38 silakan cek Pull Request #16 mas.
