### ISSUE TITLE
[BUG]. Input Langganan Baru Error

### ISSUE THREAD

**Issue by anisku11** [nafiesl/free-pmo#2]
Bagian input langganan alias subcriptions bagian  mulai sewa dan perpanjangan tidak ada datepickernya ya ??

jd eror 🐟 
![screenshot_1](https://user-images.githubusercontent.com/10329023/33127437-0b6b3486-cfbb-11e7-8b28-26f4793311e0.png)

**Comment by nafiesl** [comment]
Noted mas @anisku11, terima kasih reportnya mas. Insyaallah akan kita tambahkan datepickernya. Sementara bisa input dengan format **yyyy-mm-dd** :smiley:

**Comment by anisku11** [comment]
mantabs 👍  pokonya mah 🥇 🥇

**Comment by nafiesl** [comment]
Sudah update mas e649d81ec121302dbf8d5f532439c03be964d6b5, coba `git pull` ya. :+1:
