### ISSUE TITLE
Error while update fee payment

### ISSUE THREAD

**Issue by achmadhadikurnia** [nafiesl/free-pmo#20]
![image](https://user-images.githubusercontent.com/4408971/47082163-f4af5b80-d236-11e8-8a3f-5d55b3e7ba0e.png)

**Comment by nafiesl** [comment]
Noted mas, saya akan cek problem ini, terima kasih mas.

**Comment by achmadhadikurnia** [comment]
Siap mas.  Sama2

**Comment by nafiesl** [comment]
Sepertinya ini error karena form edit paymentnya sama dengan form edit payment biasa mas. Kita perlu buat form edit payment khusus untuk fee payment.

Trims mas sudah menemukan bug ini.

**Comment by achmadhadikurnia** [comment]
Sama-sama mas
