### ISSUE TITLE
[PROPOSAL] Fitur Bukti Bayar

### ISSUE THREAD

**Issue by achmadhadikurnia** [nafiesl/free-pmo#25]
Sedikit cerita, setelah memakai aplikasi ini selama setahun. Ada client dari pemerintahan yang meminta mencantumkan NPWP di invoicenya. Fitur NPWP langsung di eksekusi sama mas @nafiesl di #23 Terimakasih mas.

Selain itu, ada pula yang meminta bukti bayar, semacam kuitansi yang menyatakan client telah mengirim pembayaran dan kita sebagai agensi telah menerima pembayaran.

Disini ada dua macam tipe, yang tidak membutuhkan materai dan yang membutuhkan materai (1jt keatas). Referensi regulasinya bisa dilihat di Pasal 2 PP No 24 tahun 2000 tentang Perubahan Tarif Bea Materai dan Besarnya Batas Pengenaan Harga Nominal dan pasal 2 ayat 1-4 UU No 13 tahun 1985 yang mengatur perihal penggunaan materai.

### Planing penambahan fitur:
- Bukti bayar tanpa kolom materai
- Bukti bayar dengan kolom materai

**Comment by nafiesl** [comment]
Trims mas masukannya.
Tapi untuk kuitansi, sudah ada setiap kita input pembayaran mas.

![selection_18111701](https://user-images.githubusercontent.com/8721551/48661081-9250b180-eaa7-11e8-9772-8832f6958586.jpg)

![selection_18111702](https://user-images.githubusercontent.com/8721551/48661106-cd52e500-eaa7-11e8-9aa5-7081a68343e0.jpg)

Apakah seperti ini yang mas @achmadhadikurnia maksud? tetapi memang Bukti pembayaran ini belum ada tanda wajib kuitansi atau tidak. Dan record pembayaran belum ada relasi dengan invoice.

**Comment by achmadhadikurnia** [comment]
Ia mas ini cukup sepertinya. Oya saya nemuin bugs baru edit payment. nanti saya kirim issue
