### ISSUE TITLE
[BUGS] Mis match select on edit payment

### ISSUE THREAD

**Issue by achmadhadikurnia** [nafiesl/free-pmo#27]
Maaf mengganggu lagi mas @nafiesl 
Saya ingin melaporkan bugs yang saya alami

![image](https://user-images.githubusercontent.com/4408971/48672035-4105f800-eb63-11e8-88ca-668b4ebd9f1d.png)
Harusnya Fahmi yang terselect.
Setelah dilihat ternyata Fahmi dan Indoworx memiliki id (partner_id) yg sama
![image](https://user-images.githubusercontent.com/4408971/48672045-76aae100-eb63-11e8-8f11-285e8dd414a9.png)
Septerti yg di ketahui partner_id bisa sama namun partner_type bisa berbeda
![image](https://user-images.githubusercontent.com/4408971/48672063-a22dcb80-eb63-11e8-9311-f58938a9c921.png)

Sebelumnya terimakasih banyak

**Comment by nafiesl** [comment]
I see, berarti problemnya ini id vendor dengan id customer sama-sama selected ya mas. Mantap, terima kasih informasinya mas. Saya akan coba telusuri dulu.

**Comment by achmadhadikurnia** [comment]
Ia mas sma2 selected. 😁

Oya mas, trik biar html form dalam html table bisa jalan gmn ya. Saya liat di coding mas jalan tp di saya tidak bisa.

Pd umumnya sih memang tidak bisa, sudah saya contoh codingnya mas, tp knp msh ga jalan ya.

Contohnya pada input invoice, itu per rownya kan form ya.

**Comment by nafiesl** [comment]
Oh itu mas, triknya: remove Vue. Maka form per table row akan berkerja. :+1:

**Comment by achmadhadikurnia** [comment]
Remove vue gmn tuh maksudnya mas

**Comment by nafiesl** [comment]
By default kan file app.js di laravel include vuejs mas. nah itu harus dihilangkan, jadi pure jquery dan boostrap saja. Contoh di [commit repo ini](https://github.com/nafiesl/arisan/commit/a5fd06bce5c53592a5b46f2f2e81a46b1e60a74e).

**Comment by achmadhadikurnia** [comment]
oh begitu, ok ok terimakasih mas
