### ISSUE TITLE
[BUGS] CSS Break

### ISSUE THREAD

**Issue by achmadhadikurnia** [nafiesl/free-pmo#30]
Lagi2 post issue hehehe

Saya menemukan css break saat input job 
![image](https://user-images.githubusercontent.com/4408971/49322274-c8c70b80-f540-11e8-9dff-541da3da3d4b.png)

**Comment by nafiesl** [comment]
Ok mas, terima kasih, ini bisa kita perbaiki dengan mengganti label nya, mungkin akan kita ubah dari **Tanggal Selesai Target** menjadi **Target Tgl Selesai**.

**Comment by achmadhadikurnia** [comment]
Ok mas.
