### ISSUE TITLE
[BUGS] Inputan Langganan Hilang

### ISSUE THREAD

**Issue by achmadhadikurnia** [nafiesl/free-pmo#31]
Saat ada pesan error misalya semua form sudah terisi tapi lupa 1 isi harga.
Ada pesan error kan.
nah pilihan jenis langganan akan hilang dan harus diinput lagi

![image](https://user-images.githubusercontent.com/4408971/49323738-84446b80-f552-11e8-8771-1e650535babe.png)

**Comment by nafiesl** [comment]
Terima kasih mas, ini sebenarnya problem dari package [FormField](https://packagist.org/packages/luthfi/formfield). Saya sudah buat [issue](https://github.com/nafiesl/FormField/issues/4), tetapi setelah dicek ternyata problemnya dari package laravelcollective/html yang jadi dependency nya.

Jadi untuk case ini akan kita label wont fix ya mas. Nanti kalau sudah diperbaiki, kita update versi package FormField nya di composer.lock.
