### ISSUE TITLE
Very limiting character length for descriptions 

### ISSUE THREAD

**Issue by damms005** [nafiesl/free-pmo#38]
Descriptions for projects, jobs, and tasks are hard-coded. As descriptions are subjective, there should be no hard limits on them. 

Can this be addressed such that limits in the context described above are more flexible?

(maybe I will do a PR)

**Comment by nafiesl** [comment]
You mean we need change data type from varchar(255) to text @damms005?

**Comment by damms005** [comment]
Yes. But I am doing a PR now

**Comment by nafiesl** [comment]
Hello @damms005, sorry I am closing this outdated issue.
