### ISSUE TITLE
does it support multi language?

### ISSUE THREAD

**Issue by alpham8** [nafiesl/free-pmo#4]
Hi,

first of all thank you very much for that great piece of software (even if there is work in progress).

I have one question: Is this software shipped with translations into different languages than english right now? Or do you plan any multi language support?

Thanks in advice,

alpham8

**Comment by nafiesl** [comment]
Hi, thanks for your appreciation. It is a great motivation for me.

For your question, sure, it can be support for multi language. Currently we only have English (en) and Indonesian (id) lang on the project.

Check it out on this directory https://github.com/nafiesl/free-pmo/tree/master/resources/lang.

It's great if you can help to add your lang translation files for your language. Feel free to contribute by Pull Request.
