### ISSUE TITLE
Error saat update ketika no npwp kosong

### ISSUE THREAD

**Issue by achmadhadikurnia** [nafiesl/free-pmo#40]
Saat tidak ingin coba pake NPWP, saya hapus NPWP dan menampilkan error seperti ini
![image](https://user-images.githubusercontent.com/4408971/60071818-a2b7c180-9745-11e9-8754-ce9215797cb9.png)

**Comment by nafiesl** [comment]
Hmm.. oke sepertinya kita mesti convert `null` menjadi empty string "" ya. Mau contribute untuk buat PR mas @achmadhadikurnia?

**Comment by dels07** [comment]
null value dikonversi ke string kosong:
https://github.com/nafiesl/free-pmo/pull/41

**Comment by nafiesl** [comment]
Kang @dels07, siap saya cek kang :pray:
