### ISSUE TITLE
Report's Language

### ISSUE THREAD

**Issue by salihanmridha** [nafiesl/free-pmo#5]
Hello,
I am trying to change language at yearly report. It is like Januari, Pebruari, Maret. I want it as like English. I have tried in many ways. But how to solve it?

**Comment by nafiesl** [comment]
Hi @salihanmridha,

You may change it within this file :
https://github.com/nafiesl/free-pmo/blob/master/app/helpers.php#L86-L102

I think i miss this one for translation. I will update this to use laravel lang, as soon as i can.
Thanks for informing this. :+1:

**Comment by salihanmridha** [comment]
Yeah, I just did it few minute ago. :) thanks :)

**Comment by nafiesl** [comment]
Yes, sure. Thanks. :)
