### ISSUE TITLE
[BUG] Error Unable to Write in the "public/assets/imgs" directory

### ISSUE THREAD

**Issue by nafiesl** [nafiesl/free-pmo#52]
## Problem

New installation of free-pmo project on Ubuntu get an error on uploading agency logo. This might be happening to other distros, too.

Mu current local setup:
- Linux mint 18.3
- PHP 7.2
- MariaDB 10.2

## How to reproduce

1. Install **new** free-pmo project ([these steps](https://github.com/nafiesl/free-pmo#installation-steps))
2. Login as administrator
3. Go to **Agency Profile** tab
4. Click **Edit Agency**
5. Upload new logo
6. Get this error write permission problem.

![screenshot_19-10-25_005](https://user-images.githubusercontent.com/8721551/67571429-7ef1a000-f766-11e9-9298-ca5f98f655d0.jpg)

## Proposed solution

Upload logo destination goes to `storage/app/public` folder. Then we save the file path to `site_options` table (like existing). To get access to storage folder, we will need to run `php artisan storage:link`.

**Comment by agasigp** [comment]
No issue when I test on my laptop. My current laptop setup :
- Linux Mint 19.2
- PHP 7.3 with Nginx (Valet Linux)
- Mariadb 10.4

**Comment by nafiesl** [comment]
Yes correct @agasigp, I am reviewing your PR in #53.
