### ISSUE TITLE
Error composer install

### ISSUE THREAD

**Issue by wmomesso** [nafiesl/free-pmo#55]
Generating optimized autoload files
Class Illuminate\Foundation\ComposerScripts is not autoloadable, can not call post-autoload-dump script
> @php artisan package:discover
PHP Warning:  require(/home/wmomesso/Documentos/ManagerProjectLaravel6/free-pmo/free-pmo/vendor/composer/../laravel/framework/src/Illuminate/Foundation/helpers.php): failed to open stream: No such file or directory in /home/wmomesso/Documentos/ManagerProjectLaravel6/free-pmo/free-pmo/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/home/wmomesso/Documentos/ManagerProjectLaravel6/free-pmo/free-pmo/vendor/composer/../laravel/framework/src/Illuminate/Foundation/helpers.php' (include_path='.:/usr/share/php') in /home/wmomesso/Documentos/ManagerProjectLaravel6/free-pmo/free-pmo/vendor/composer/autoload_real.php on line 66
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

**Comment by nafiesl** [comment]
Hi @wmomesso, do you run `composer install` on your existing/installed free-pmo project, or on new clone?

**Comment by wmomesso** [comment]
Hi @nafiesl new clone

**Comment by nafiesl** [comment]
Ok I will try to reproduce it, by installing new clone on my localhost.

**Comment by nafiesl** [comment]
@wmomesso, I am having no issue on `composer install` command on the new clone.

![screen_19-12-09_004](https://user-images.githubusercontent.com/8721551/70444850-7e725600-1ad5-11ea-8268-58871c2005d0.jpg)

This project uses `laravel/framework (v6.0.4)`. Have you fulfill this server requirement on you local machine?

**Comment by wmomesso** [comment]
Excuse, i not clear composer cache, now installer correctly. thanks.
