### ISSUE TITLE
error saat pekerjaan dari project lain tidak di check list langsung klik tambah

### ISSUE THREAD

**Issue by yopie79** [nafiesl/free-pmo#56]
![error_penugasan dari project lain](https://user-images.githubusercontent.com/59214862/71429655-581a0080-26fa-11ea-9cbd-27c2dcdbf7c6.jpg)
mohon bantuannya, terima kasih.

**Comment by nafiesl** [comment]
Halo mas @yopie79, sepertinya case nya sama dengan ini https://github.com/nafiesl/free-pmo/issues/45 ya?

**Comment by yopie79** [comment]
maaf mas @nafiesl kl yang issue #45 sebagian data checklistnya terisi ya, kl ini tidak dipilih sama sekali, seperti yang saya capture ya
![error_penugasan dari project lain1 (no pilih data)](https://user-images.githubusercontent.com/59214862/71432003-bbab2a80-2708-11ea-98cf-c91dbe9eb8e2.jpg)

**Comment by yopie79** [comment]
Maaf mas @nafiesl , kl #45 itu sebagian datanya terisi ya, kl ini belum dipilih sama sekali langsung add job, saya capture ya 
![error_penugasan dari project lain1 (no pilih data)](https://user-images.githubusercontent.com/59214862/71432115-bc908c00-2709-11ea-9b97-67b1f100e683.jpg)
seperti diatas mas, lgsng tampil error tadi makasih.

**Comment by nafiesl** [comment]
Ok mas @yopie79, confirm ini bug, saya bisa reproduce juga. Akan saya coba perbaiki.

**Comment by yopie79** [comment]
baik mas, trims

**Comment by yopie79** [comment]
Problem Solved, terima kasih mas

**Comment by nafiesl** [comment]
Oke sama2 mas @yopie79. :pray:
