### ISSUE TITLE
error saat backups

### ISSUE THREAD

**Issue by yopie79** [nafiesl/free-pmo#58]
Selamat Pagi Mas Nafies,

info mas ada error saat back up files, seperti gambar berikut ya, mohon bantuannya
![error_backups](https://user-images.githubusercontent.com/59214862/71565969-2502b300-2ae6-11ea-8c57-357f7b8451ce.jpg)

Terima kasih

**Comment by nafiesl** [comment]
Halo mas @yopie79, mungkin ini bisa bantu jawab problemnya mas:

- https://stackoverflow.com/questions/49788144/general-error-mysqldump-is-not-recognized-as-an-internal-or-external-comma/49788342
- https://github.com/schickling/laravel-backup/issues/60

**Comment by yopie79** [comment]
baik mas, terima kasih infonya.

**Comment by alhaqqonny** [comment]
> Halo mas @yopie79, mungkin ini bisa bantu jawab problemnya mas:
> 
> * https://stackoverflow.com/questions/49788144/general-error-mysqldump-is-not-recognized-as-an-internal-or-external-comma/49788342
> * [schickling/laravel-backup#60](https://github.com/schickling/laravel-backup/issues/60)

Pagi, Mas Nafies.
Saya mengalami kegagalan di menu backup-manager, dan sudah mengikuti langkah diatas. Adakah solusi yang lain, Mas? Terima kasih.

**Comment by nafiesl** [comment]
Halo mas @alhaqqonny, errornya sama mas?
Bisa di screenshot error terakhir setelah mencoba solusi di atas?

**Comment by alhaqqonny** [comment]
![image](https://user-images.githubusercontent.com/8564195/107166462-acf50500-69e8-11eb-9f6f-a5cd7d8b37d5.png)


Ini, mas. Sudah saya coba yang referensi 1 dan 2 diatas dari Mas Nafies. Terima kasih.

**Comment by nafiesl** [comment]
Coba solusi ini mas @alhaqqonny 

https://www.youtube.com/watch?v=-rzQv9DLfDo

**Comment by alhaqqonny** [comment]
Yang di environment variables sudah pernah saya tambahkan mas. Kemarin akhirnya saya coba uninstall xampp, dan fresh install lagi, mas. Alhamdulillah backup & restore bisa jalan via terminal. Ini nanti saya coba lagi untuk yg di web nya langsung. Terima kasih.

**Comment by orcome** [comment]
Kendala yang ditemukan di menu backup dan restore menggunakan OS Windows 10

1. Pesan Error :
'mysqldump' is not reconized as an internal or external command, operable program or batch file

Solusi :
- Tentukan path lokasi folder bin dari mysql, contoh kasus saya ada di C:\xampp\mysql\bin, path mungkin berbeda, selanjutnya copy path tersebut.
- Pada Window Explore : This PC->(klik kanan)->properties
- Muncul form baru : Advanced system settings
- Muncul form System Properties : Advanced->Environment Variables
- Muncul form Environment Variables : Pilih bagian system variables->(double klik) pada Path
- Muncul form Edit environment variable : New->(paste path)->C:\xampp\mysql\bin
- Selanjutnya Ok.


2. Pesan Error :
'gzip' is not reconized as an internal or external command, operable program or batch file

Solusi :
- Download dan Install Gzip (yang saya gunakan pada kasus ini gzip 1.3.12)
- Install seperti biasa, saya menginstall di path C:\Program Files (x86)\GnuWin32
- Pastikan instalasi sampai selesai
- Selanjutnya Buka Window Explore : This PC->(klik kanan)->properties
- Muncul form baru : Advanced system settings
- Muncul form System Properties : Advanced->Environment Variables
- Muncul form Environment Variables : Pilih bagian system variables->(double klik) pada Path
- Muncul form Edit environment variable : New->(paste path)->C:\Program Files (x86)\GnuWin32\bin
- Selanjutnya Ok.
- Sebelum mencoba menu backup restore, PC harus direstart terlebih dahulu

Sekian infonya semoga membantu. terima kasihh ^_^

**Comment by nafiesl** [comment]
Terima kasih mas @orcome sudah berkenan share solusi :pray:
