### ISSUE TITLE
[BUG] Tombol Delete File Document Project

### ISSUE THREAD

**Issue by dhifreeze** [nafiesl/free-pmo#59]
Dear Mr. Nafies,

Mohon dibantu untuk menambahkan tombol hapus/delete dibagian List Dokumen Project, karena saat ini tombol tersebut belum tersedia.

Terima Kasih
![CapturePMO](https://user-images.githubusercontent.com/40667083/71582343-c4569300-2b44-11ea-9067-55bce5797506.PNG)

**Comment by nafiesl** [comment]
Halo mas @dhifreeze, di Detail Project => List Dokumen mestinya sudah ada tombol hapus filenya mas. Ini screenshot terbarunya.

![screen_19-12-31_001](https://user-images.githubusercontent.com/8721551/71589672-a1d27300-2b60-11ea-83b2-56561f14ac7a.jpg)

Apa mungkin source code mas belum update ya, karena fitur delete file ini sudah dibuat sekitar 10 bulan yang lalu di commit ini https://github.com/nafiesl/free-pmo/commit/6195f76e26eb65980989c76989af036dfb7f674f.
