### ISSUE TITLE
PROPOSAL Fiture Module

### ISSUE THREAD

**Issue by yopie79** [nafiesl/free-pmo#60]
Selamat Pagi Mas Nafies,

Saya mau usul saja mas, setelah saya baca dan pelajari konsep appnya ini sudah bagus tapi apakah ada kemungkinan aplikasi ini dikembangkan lagi dengan menambahkan fiture module :                                                               
1. RAB untuk masing-masing projects, dimana RAB itu sendiri terbagi menjadi 2 antara lain ; RAB External dan RAB Internal yang bisa dicetak atau download.
2. Manage penempatan SDM di masing-masing proyek, sehingga cost yang dikeluarkan untuk biaya SDM atau beban yang lain bisa cocok dengan RAB yang dibuat.
3. Role pengguna sebaiknya ditambahkan lagi misl : root untuk full menu, 
    role administrator untuk mengelola/aprove dan monitoring pekerjaan/tugas (worker)
    role worker saran saya sebaiknya juga bisa menginput daftar pekerjaan dan tugas yang akan mereka kerjakan tidak hanya melalui role administrator saja, supaya lebih flexible.

Demikian Mas Nafies, sedikit masukan dari saya dengan harapan app ini akan menjadi lebih bagus lagi kedepannya, mohon maaf jika ada kesalahan.
Trims.

**Comment by nafiesl** [comment]
Halo mas @yopie79, mohon maaf setahun kemudian saya baru respons usulan mas ini :pray: 

1. Untuk RAB, sistem ini sudah memiliki fitur serupa RAB yaitu penentuan harga pada setiap Job di dalam sebuah project, hanya saja tidak ada pembagian RAB internal dan external seperti yang mas maksudkan. Untuk versi open source sistem ini, saya belum ada agenda untuk menambahkan fitur RAB secara detail seperti demikian.
2. Untuk manajemen SDM, sudah ada fitur serupa juga, yaitu pada saat kita input/edit Job, kita bisa menentukan siapa worker nya, dalam hal ini PIC yang bertugas/bertanggung jawab atas Job tersebut. Untuk biaya yang biaya yang dikeluarga per job atau per SDM, saat ini tidak belum ada support untuk ke arah situ untuk Free PMO open source.
3. Untuk penambahan role dan pembagian hak akses seperti ini, hemat saya tidak semua pengguna Free PMO membutuhkannya, kecuali memang banyak yang mengusulkan demikian, saya bisa pertimbangkan untuk akomodir.

Pada dasarnya usulan di atas dapat mas kembangkan sendiri sesuai kebutuhan perusahaan mas @yopie79. Jangan ragu untuk menghubungi saya melalui email nafiesL@gmail.com atau telegram @nafiesL jika ingin diskusi lebih lanjut untuk development project PMO Khusus sesuai kebutuhan mas @yopie79.

Terima kasih.

**Comment by yopie79** [comment]
Nga papa mas, terima kasih juga atas responnya, nanti kalo saya ingin
diskusi lanjutan saya kabar-kabari lagi ya🙏

**Comment by nafiesl** [comment]
Ok siap mas @yopie79, kita close dulu issuenya ya. Terima kasih mas.
