### ISSUE TITLE
tidak bisa install pada xampp v3.2.2 php 7.3.8 windows 7

### ISSUE THREAD

**Issue by kakferryse** [nafiesl/free-pmo#62]
Saya sudah melakukan proses install dari panduan
https://github.com/nafiesl/free-pmo/blob/master/README.id.md
langkah 1-4 berhasil.
Langkah 5 muncul pesan error ini 
![Screenshot_5](https://user-images.githubusercontent.com/41139461/84592782-48da6b00-ae72-11ea-91d7-2310f20bb5da.jpg) 
Langkah 6 juga error 
![Screenshot_6](https://user-images.githubusercontent.com/41139461/84592816-8b03ac80-ae72-11ea-8fb0-5c4ba6cfa8e4.jpg)
hingga seterusnya jadi tidak bisa..
tolong dibantu,..trims

**Comment by nafiesl** [comment]
Halo mas @kakferryse, kalau dilihat dari proses di atas, sepertinya mas **belum sukses di tahap nomor 4.** Yaitu menduplikat file `.env.example` menjadi file `.env`. Karena pesannya file `.env` tidak ditemukan.

Coba mas cek apakah ada file `.env` di dalam foldernya?

![screenshot_2020-06-14_001](https://user-images.githubusercontent.com/8721551/84593117-ecc91400-ae7c-11ea-8419-9394a9b96540.jpg)

Jika belum ada, maka coba mas lakukan:
1. Buka project dengan text editor seperti sublime text atau vscode.
2. Buat file `.env` (tanpa nama file, hanya extensi .env saja).
3. Copy isi file `.env.example` yang ada di folder.
4. Paste ke file `.env` yang baru dibuat tadi.
5. Kemudian coba **lanjutkan langkah ke 5** apakah berhasil.

**Comment by kakferryse** [comment]
sudah ada mas seperti ini 
![Screenshot_7](https://user-images.githubusercontent.com/41139461/84594068-e4230e80-ae79-11ea-9733-f8f8efc8c9d6.jpg)
jadi ada 2 file .env dan .env.example tp ttp tdk bisa

**Comment by nafiesl** [comment]
Nama filenya masih keliru mas disitu namanya: `.env.env` seharusnya `.env` saja.
