### ISSUE TITLE
[PROPOSAL] Penambahan Assignment Task untuk individual user

### ISSUE THREAD

**Issue by diorz38** [nafiesl/free-pmo#8]
Saat ini assignment hanya untuk untuk Job, jika ditambahkan opsi untuk assignment task untuk individual user, akan sangat membantu, setidaknya untuk saya.

Misalkan Job untuk si A, dan si A dapat assign Task kepada user lainnya, semacam tim kecil.

terimakasih

Saya coba modifikasi sendiri, tetapi karena masih baru di Laravel, dan struktur nya sudah cukup advance, saya masih ragu, dan sekarang ini sedang coba memahami alur programnya.

**Comment by ad3n** [comment]
:+1:

**Comment by nafiesl** [comment]
Mas @diorz38, terima kasih untuk masukannya, usulan ini akan saya tampung dulu.
Tetapi dalam waktu dekat saya belum berencana untuk menambahkan fitur task assignment ini ke Free-PMO.

Mas @diorz38 tetap bebas melakukan improvement Free PMO (clone/fork) sesuai kebutuhan team mas @diorz38.

Terima kasih mas.

**Comment by nafiesl** [comment]
Hehe.. faham saya mas @diorz38. Ada beberapa teman juga yang kontak ke saya untuk meminta improvement project ini menurut sistem di perusahaan mereka. Tetapi hanya sebagian yang saya sepakati untuk dibuat menjadi fitur di Free PMO.
Tujuannya agar Free PMO tetap memenuhi kebutuhan pengelolaan proyek secara umum, bukan untuk spesifik sebuah instansi saja. :grin:
Untuk fitur-fitur khusus, opsi pertama, semua developer bebas mengembangkan Free-PMO sesuai kebutuhannya. Opsi kedua, mas @diorz38 bisa hubungi saya secara personal dan diskusi untuk pengembangan sesuai kebutuhan (semacam premium service).

Untuk roles permission di database, sebenarnya awal dari project ini menerapkan seperti itu mas (project ini dimulai dari repo [Laravel-Starter-Kit](https://github.com/nafiesl/Laravel-Starter-Kit) ini, yang mengadopsi Role Rermission dari database). Tetapi semakin ke sini, ada pertimbangan khusus sehingga role dan permission di Free PMO diubah menggunakan laravel policy object saja (tidak dengan database lagi).

Pertimbangannya:
1. Role permission dengan database tidak ikut dan tertuang di source code.
2. Role permission dengan database **hanya mengatur** user boleh melakukan sesuatu atau tidak, tetapi **tidak bisa** mengatur permission untuk **kondisi khusus** (misal Worker A hanya bisa mengelola jobnya sendiri, tidak bisa mengelola job orang lain, walaupun di project yang sama).
3. Untuk kebutuhan khusus tersebut, **harus declare di policy object** lagi (jadinya ada dualisme peraturan, permission di database, dan policy object).
4. Role permission di policy object sangat mudah dibuat testingnya, [contohnya ini](https://github.com/nafiesl/free-pmo/blob/master/tests/Unit/Policies/ProjectPolicyTest.php).
5. Dengan membaca policy object di source code, semua developer yang terlibat dalam development project ini mudah memahami hak akses masing-masing tipe user.

Karena pertimbangan itu, saya putuskan semua role permission diatur di policy object saja. Seperti itu penjelasanya mas.

Terima kasih banyak untuk apresiasinya mas, semakin semangat saya untuk maintain dan mengembangkan repo ini. :grinning:
