### ISSUE TITLE
Is it posssible to pay 

### ISSUE THREAD

**Issue by ugintl** [nafiesl/free-pmo#86]
Is it possible to pay team members/freelancers through paypal?

**Comment by nafiesl** [comment]
Hi @ugintl. The payment feature on this project only for transaction entries, so we can log every project incomes and spendings. We don't have plan to develop the send/receive payment in this project. Feel free to implement it on your clone. 👍

**Comment by ugintl** [comment]
How much would it cost if someone asks you to implement this feature?

**Comment by nafiesl** [comment]
@ugintl I can't answer right now, as I am not available to take a new project for the next couple of months, sorry.

**Comment by nafiesl** [comment]
Hello @ugintl, I am closing this issue, feel free to re-open if you have further questions.
