### ISSUE TITLE
Error "Trying to get property 'name' of non-object"

### ISSUE THREAD

**Issue by omdons** [nafiesl/free-pmo#87]
Dear,

Ada masalah saat klik pembayaran setelah upload dokumen "Trying to get property 'name' of non-object".
![image](https://user-images.githubusercontent.com/47166543/177103115-ae2e71e9-6e6f-47d5-a00b-fbc3af19cb42.png)

Mohon Advice .. trm kasih

Salam,
DK

**Comment by nafiesl** [comment]
@omdons kalau dilihat dari errornya, sepertinya ada data partner (customer atau vendor) yang dihapus atau hilang dari sistem.

Bisa cek di source code bagian ini:
https://github.com/nafiesl/free-pmo/blob/master/resources/views/projects/payments.blade.php#L40

Bagian kode itu memanggil nama partner (customer atau vendor), tetapi object partner bernilai null.

Solusinya:
- Dari database, harus dicari tahu record pembayaran/payment mana yang partner_id nya hilang (lihat `partner_type` nya).
- Kemudian value `payment_id` nya diset ke record customer/vendor yang ada.

screenshot bagian kode yang error.

![screen_2022-07-04_011](https://user-images.githubusercontent.com/8721551/177148094-b0ca3458-8b51-4829-a2d8-bc6b3b5624c3.jpg)

**Comment by nafiesl** [comment]
@omdons sebagai alternatif, coba ubah baris error di file view tersebut dari

```
<td>{{ $payment->partner->name }}</td>
```
Menjadi
```
<td>{{ optional($payment->partner)->name }}</td>
```

Persisnya di file ini: https://github.com/nafiesl/free-pmo/blob/master/resources/views/projects/payments.blade.php#L40.

Seharusnya errornya akan hilang, tetapi nanti nama partner yang hilang dari database akan kosong.

**Comment by nafiesl** [comment]
@omdons, issue ini saya close, jika ada pertanyaan lanjutan, silakan re-open ya.
