### ISSUE TITLE
Request di Bagian Daftar Job

### ISSUE THREAD

**Issue by nurhamdaniab** [nafiesl/free-pmo#88]
Apakah bisa ketika dibagian Input Job langsung Input Taks saja tanpa ada embel2 Detail Job ?

**Comment by nafiesl** [comment]
Halo mas @nurhamdaniab mohon maaf issue ini terlewat oleh saya.

Kalau secara struktur table, tidak memungkinkan untuk input task langsung tanpa lewat job mas.
