### ISSUE TITLE
[PROPOSAL] Fitur Duplikat Invoice

### ISSUE THREAD

**Issue by nafiesl** [nafiesl/free-pmo#9]
Ada beberapa project yang memiliki subscription (langganan), misalnya Maintenance Bulanan, Domain, atau Hosting. Untuk subscription tersebut, kita bisa membuatkan invoice kepada klien.

Contoh Kasus:
Misal maintenance bulanan yang dibayar per 3 bulan.
Bulan **Januari** kita membuat invoice dengan item berikut :
1. Maintenance ... Januari 2018.
2. Maintenance ... Pebuari 2018.
3. Maintenance ... Maret 2018.

Bulan **April** kita membuat invoice dengan item berikut :
1. Maintenance ... April 2018.
2. Maintenance ... Mei 2018.
3. Maintenance ... Juni 2018.

Untuk saat ini, saat membuat invoice, kita mengisi item satu persatu. Akan lebih baik, jika kita memiliki fitur **Duplikat Invoice**. Kita **duplikat invoice Januari**, kemudian ubah nama bulan per item. Jadi ketika membuat invoice untuk item-item yang serupa, prosesnya bisa lebih menghebat waktu (dibandingkan kita harus menulis ulang item satu persatu).

Rencananya :
1. Ada tombol "Duplikat Invoice" pada halaman detail Invoice.
2. Invoice akan terduplikat menjadi Draft Invoice (dalam session).
3. Data customer pada invoice sama dengan data customer invoice sebelumnya.
4. User dapat mengubah item sesuai kebutuhan.
5. Simpan Draft Invoice dengan nomor invoice baru (dalam database).

**Comment by ad3n** [comment]
@nafiesl saran saja, kalau bisa tidak perlu menyimpan di session tapi langsung saya copy dan simpan ke DB (INSERT INTO x VALUES(SELECT * FROM)) kira-kira begitu operasinya jadi nanti tinggal edit menggunakan tombol edit, sehingga ga perlu ada kontak dengan user (pakai form, dsb)

**Comment by nafiesl** [comment]
Bisa juga sih mas Sur, berarti nanti setelah duplikat, otomatis langsung dapat nomor invoice ya (karena langsung disimpan ke DB).

Kebetulan fitur Draft Invoice (yang disimpan di session) ini sudah ada, untuk proses membuat invoice baru.

Nanti kita coba lihat mas. Terima kasih banyak mas Sur.

**Comment by ad3n** [comment]
Iya, nomer invoice biasanya kan otomatis dan ada polanya, tinggal disesuaikan aja... jadi biar memangkas proses aja... Bisa disimpan sebagai draft dulu biar bisa diedit sesuai dengan status yang seharusnya di sistem... Soalnya kan ane ga tau ada berapa status di sini

**Comment by nafiesl** [comment]
Iya mas Sur.

Oh ya. Di sistem ini, invoicenya belum ada statusnya. Jadi belum ketahuan mana invoice yang sudah dibayar, mana yang belum. Mestinya ada ya? Mungkin nanti setelah ini kita bisa buat status invoice juga mas. :+1:

**Comment by ad3n** [comment]
Harusnya sih ada...
